### ISSUE TITLE
带 params 的函数不会用

### ISSUE THREAD

**Issue by weakish** [Pana/PM25.in#2]
``` coffee
pm25.city25({city: '北京'}, (err, data) -> console.log(err, data))
```

报错如下：

```
TypeError: object is not a function
  at Object.city25 (/usr/lib/node_modules/pm25in/lib/pm25.js:38:24)
  at repl:1:10
  at REPLServer.replDefaults.eval (/usr/lib/node_modules/coffee-script/lib/coffee-script/r
epl.js:33:42)
  at repl.js:239:12
  at Interface.<anonymous> (/usr/lib/node_modules/coffee-script/lib/coffee-script/repl.js:
66:9)
  at Interface.emit (events.js:117:20)
  at ReadStream.<anonymous> (/usr/lib/node_modules/coffee-script/lib/coffee-script/repl.js
:89:13)
  at ReadStream.emit (events.js:117:20)
  at emitKey (readline.js:1095:12)
  at ReadStream.onData (readline.js:840:14)
  at ReadStream.emit (events.js:95:17)
  at ReadStream.<anonymous> (_stream_readable.js:764:14)
  at ReadStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:426:10)
  at emitReadable (_stream_readable.js:422:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at ReadStream.Readable.push (_stream_readable.js:127:10)
  at TTY.onread (net.js:528:21)
```

**Comment by Pana** [comment]
npm上的code 有点旧了, 刚publish 个新版, 你可以安装最新(0.0.4)或下载源代码使用
